### ISSUE TITLE
InjectableFilterAttribute

### ISSUE THREAD

**Issue by boriscallens** [lozanotek/mvcturbine#1]
Has something happened to InjectableFilterAttribute?
I updated the libraries and now InjectableFilterAttribute cannot be resolved anymore. I checked the samples provided and noticed the same problem existed there too..

Using MVCTurbine 2.1 with MVC2

**Comment by darrencauthon** [comment]
You won't be able to find them, but the good news is:  You don't need them any longer.  MVC Turbine supports property injection on MVC filters now, so if you create a plain ol' MVC filter and expose your dependencies as setter properties with whatever property injection attributes your particular container requires, you should be good to go.  

Does this help?  If you need help changing your filter, we can help.

**Comment by boriscallens** [comment]
Aha, that is good news. I'll check it out. Thanks

**Comment by boriscallens** [comment]
Can't find a way to close this without comment, hence this unnecessary redundancy overhead.
